services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_VERSION: ${APP_VERSION:-dev}
    container_name: shoutout-server
    restart: unless-stopped
    ports:
      - "3001:3001"
    env_file:
      - ./.env
    volumes:
      - server_config:/app/config

  caddy:
    image: caddy:2
    container_name: shoutout-caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - server

volumes:
  server_config:
  caddy_data:
  caddy_config:
